# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dFs-CyHfgVV6MDv1FJ-5VXGTwjzZONyo
"""

pip install nltk

pip install newspaper3k

from newspaper import Article

import random
import string

from sklearn.feature_extraction.text import CountVectorizer

import nltk

from sklearn.metrics.pairwise import cosine_similarity

import numpy as np

import warnings
warnings.filterwarnings('ignore')

#download the punkt package

nltk.download('punkt',quiet=True )

#get info from article 
article=Article('https://www.digitalocean.com/community/tutorials/an-introduction-to-machine-learning')
article.download()
article.parse()

article.nlp()
corpus=article.text

#print collected data

print(corpus)

#tokenize

text=corpus
sentence_list=nltk.sent_tokenize(text)

#print list of sentences

print(sentence_list)

#greeting response

def greeting_response(text):
  text=text.lower()
  #bot greetings
  bot_greetings=['hi!' ,'hey there!','hello!','nice to see you!','heya!','hey!','good to have you here']
   #user greetings 
  user_greetings=['hey','hi','hello','hey there','wassup' , 'ssup','whats up']
  for word in text.split():
    if word in user_greetings:
      return random.choice(bot_greetings)

def index_sort(list_var):
    length = len(list_var)
    list_index = list(range(0, length))
 
    x = list_var
    for i in range(length):
        for j in range(length):
            if x[list_index[i]] > x[list_index[j]]:
                #Swap
                temp = list_index[i]
                list_index[i] = list_index[j]
                list_index[j] = temp
 
    return list_index

#creating bots output

def bot_response(user_input):
  user_input=user_input.lower()
  sentence_list.append(user_input)
  bot_response=''
  cm=CountVectorizer().fit_transform(sentence_list)
  similarity_scores=cosine_similarity(cm[-1],cm)
  similarity_scores_list=similarity_scores.flatten()
  index=index_sort(similarity_scores_list)
  index=index[1:]
  response_flag=0
  j=0    #return top to similar sent to user input 
  for i in range(len(index)):
    if similarity_scores_list[index[i]] >0.0:
      bot_response = bot_response + ' '+ sentence_list[index[i]]
      response_flag=1
      j=j+1
      if j>2:
        break

  if response_flag==0:
    bot_response=bot_response+' '+ ' SORRY I DID NOT UNDERSTAND YOU :('
  sentence_list.remove(user_input)
  return bot_response





print("KoalaBot:hello i am KoalaBot. I am here to answer your questions regarding machine learning!")
exit_list= ['exit' ,'goodbye' ,'bye','cya' ,'see you later','break','ttyl','talk to you later','gtg','got to go','brb','be right back','quit','ok']
while(True):
  user_input=input()
  if user_input.lower() in exit_list :
    print("KoalaBot:Talk to you later! Keep Learning!")
    break
  else:
    if(greeting_response(user_input)!= None):
      print('KoalaBot:' + ' ' + greeting_response(user_input))
    else:
      print('KoalaBot:' + bot_response(user_input))











